
DROP TABLE USERS IF EXISTS;

create table USERS (
                       userId bigint generated by default as identity,
                       PASSWORD varchar(255),
                       ROLE varchar(255),
                       USERNAME varchar(255)
);

INSERT INTO USERS (userId, USERNAME, PASSWORD, ROLE)
VALUES (NULL, 'user', 'user', 'ROLE_USER');